{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "tasks-svc.fullname" . }}-jwt
  namespace: {{ .Release.Namespace }}
  labels: {{- include "tasks-svc.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: {{ include "tasks-svc.fullname" . }}-jwt
    creationPolicy: Owner
  data:
    - secretKey: jwt_secret
      remoteRef:
        key: {{ .Values.externalSecret.jwtSsmPath }}
{{- end }}
