{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "tasks-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "tasks-svc.labels" . | nindent 4 }}
spec:
  {{- if hasKey .Values.pdb "maxUnavailable" }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else if hasKey .Values.pdb "minAvailable" }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- else }}
  maxUnavailable: 0
  {{- end }}
  selector:
    matchLabels: {{- include "tasks-svc.selectorLabels" . | nindent 6 }}
{{- end }}
