apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - { name: frontend }
          - { name: auth-svc }
          - { name: tasks-svc }
          - { name: notifier-svc }
  template:
    metadata:
      name: 'dev-{{ .name }}'
      labels:
        env: dev
    spec:
      project: default
      sources:
        - repoURL: https://github.com/alusigmi/devops-orchestration.git
          targetRevision: main
          ref: values
        - repoURL: https://github.com/alusigmi/devops-orchestration.git
          targetRevision: main
          path: 'charts/{{ .name }}'
          helm:
            releaseName: '{{ .name }}'
            valueFiles:
              - values.yaml
              - $values/gitops/overlays/dev/_common.yaml
              - '$values/gitops/overlays/dev/{{ .name }}.yaml'
      destination:
        server: https://kubernetes.default.svc
        namespace: dev
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
          - PruneLast=true
