image:
  repository: 164856787183.dkr.ecr.us-east-1.amazonaws.com/usf-devops/ai-bot
  tag: git-98782ca09ba9
  digest: sha256:34cade26fe8c4272ae74d578ca960146901a5ae9564a9550a46afe85bc82ab49
ingress:
  enabled: true
  host: ai-bot.nonprod.calmloop.space
  certificateArn: ''
serviceAccount:
  irsaRoleArn: arn:aws:iam::164856787183:role/usf-devops-nonprod-ai-bot
externalSecret:
  enabled: true
  ssmPathPrefix: /devops/ai-bot
config:
  claudeModel: claude-sonnet-4-5
  clusterName: usf-devops-nonprod
