apiVersion: v1
kind: Service
metadata:
  name: ai-bot
  namespace: {{ .Release.Namespace }}
  labels: {{- include "ai-bot.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "ai-bot.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
