{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "auth-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "auth-svc.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels: {{- include "auth-svc.selectorLabels" . | nindent 6 }}
{{- end }}
