apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-svc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels: {{- include "auth-svc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector: {{- include "auth-svc.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "auth-svc.fullname" . }}-canary
  namespace: {{ .Release.Namespace }}
  labels: {{- include "auth-svc.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector: {{- include "auth-svc.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
